# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='owned_record',
            new_name='OwnedRecord',
        ),
        migrations.RenameField(
            model_name='ownedrecord',
            old_name='record',
            new_name='record_fk',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='release_year',
            new_name='release_date',
        ),
    ]
