# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170325_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownedrecord',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['number']},
        ),
    ]
