# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170402_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='band_fk',
        ),
        migrations.RemoveField(
            model_name='record',
            name='genre_fk',
        ),
        migrations.AddField(
            model_name='record',
            name='bands',
            field=models.ManyToManyField(to='music.Band'),
        ),
        migrations.AddField(
            model_name='record',
            name='genres',
            field=models.ManyToManyField(to='music.Genre'),
        ),
    ]
