# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170403_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='label',
            name='address',
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='source',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='modify_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre_modify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
