# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0009_track_feat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('like_counter', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_create_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_modify_by', to=settings.AUTH_USER_MODEL)),
                ('record_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Record')),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='feat',
            field=models.ManyToManyField(blank=True, to='music.Band'),
        ),
    ]
