# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20170411_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
    ]
