# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
            preserve_default=False,
        ),
    ]
