# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_label_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
