# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20170418_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='image',
            field=models.ImageField(blank=True, upload_to='labels'),
        ),
    ]
